feat: add routing structure
whattablackhole/rslang-archive- pull request #17
Opened 2021-03-23 19:28 UTC by nofishtou

1.  Task: add routing structure.
2.  Done: 23.03.2021.

2021-03-24 07:27 UTC, whattablackhole approved these changes

2021-03-24 12:46 UTC, Nikitzu requested changes
Remove all empty constructors

2021-03-24 12:46 UTC, Nikitzu commented on rslang/src/app/games/savannah/components/savannah-page/savannah-page.component.ts
> +  constructor() {}
remove

2021-03-25 09:33 UTC, nofishtou commented on rslang/src/app/games/savannah/components/savannah-page/savannah-page.component.ts
> +  constructor() {}
done

2021-03-25 10:33 UTC, merged