[Shared] Base service implementation
whattablackhole/rslang-archive- pull request #25
Opened 2021-03-26 09:32 UTC by whattablackhole

2021-03-26 09:39 UTC, Nikitzu requested changes

2021-03-26 09:39 UTC, Nikitzu commented on rslang/src/app/shared/models/http-options.model.ts
> +  body?: Word | Word[];
Really only Word or Words? There wont be any other types?

2021-03-26 09:39 UTC, Nikitzu commented on rslang/src/app/shared/services/base-action.service.ts
> +  data$!: Observable<T>;
There is no data during action

2021-03-26 09:39 UTC, Nikitzu commented on rslang/src/app/shared/services/base-data.service.ts
> +    this.data$ = this.subject.asObservable();
Use constructor

2021-03-26 09:39 UTC, Nikitzu commented on rslang/src/app/shared/services/base-data.service.ts
> +  data$!: Observable<T>;
not necessary property. remove !

2021-03-26 09:39 UTC, Nikitzu commented on rslang/src/app/shared/services/words-mockdata.service.ts
> +export class WordsDataService {
why it is not extended with Base?

2021-03-26 09:39 UTC, Nikitzu commented on rslang/src/app/shared/constants/base-url.ts
> +export const BASE_URL = 'https://afternoon-falls-25894.herokuapp.com';
if you will add abstraction above HTTP CLIENT this const can be moved there as soon as it will be the only place of usage.

2021-03-27 21:05 UTC, Anntol commented on rslang/src/app/shared/constants/base-url.ts
> +export const BASE_URL = 'https://afternoon-falls-25894.herokuapp.com';
Please change it to https://rslang-team4-whattablackhole.herokuapp.com

2021-03-28 07:33 UTC, Nikitzu requested changes

2021-03-28 07:33 UTC, Nikitzu commented on rslang/src/app/shared/models/callback-object.model.ts
> +  onError: Function;
I belive all properties here can be optionsl because it can be a case when there will be no callbacks needed.

2021-03-28 07:33 UTC, Nikitzu commented on rslang/src/app/shared/services/base-action.service.ts
> +  abstract callbackObject: callbackObject;
Better to make it not a service property bu a method parameter in a particular realization. As soon as almost all action will be invoked from components it is better to have possibility to create callback in the component and pass it to service

2021-03-28 07:33 UTC, Nikitzu commented on rslang/src/app/shared/services/base-action.service.ts
> +  postData(
why post?

2021-03-28 07:33 UTC, Nikitzu commented on rslang/src/app/shared/services/base-data.service.ts
> +      .subscribe((data: T) => {
Are you sure that data will be T and HttpResponse?

2021-03-28 07:33 UTC, Nikitzu commented on rslang/src/app/shared/services/base-action.service.ts
> +  abstract path: string;
better to make it an option because action service can contain a lot of different actions and it is a bad approach to reassign the same property

2021-03-28 07:44 UTC, kastrubait commented on rslang/src/app/shared/services/base-action.service.ts
> +  abstract path: string;
In my branch this is done partially

2021-03-28 19:02 UTC, whattablackhole commented on rslang/src/app/shared/services/base-data.service.ts
> +      .subscribe((data: T) => {
data will be T and not HttpResponse, you mean?

2021-03-29 08:50 UTC, Nikitzu requested changes

2021-03-29 08:50 UTC, Nikitzu commented on rslang/src/app/shared/services/word-data.service.ts
> +  getPath = (id: string) => `${BASE_URL}/words/${id}`;
unused property

2021-03-29 08:50 UTC, Nikitzu commented on rslang/src/app/shared/services/words-data.service.ts
> +  getPath = () => `${BASE_URL}/words`;
unused

2021-03-29 08:50 UTC, Nikitzu commented on rslang/src/app/shared/services/base-data.service.ts
> +  abstract getPath: Function;
unused

2021-03-29 08:50 UTC, Nikitzu commented on rslang/src/app/shared/services/base-action.service.ts
> +  abstract getPath: Function;
unused

2021-03-29 11:08 UTC, Nikitzu requested changes

2021-03-29 11:08 UTC, Nikitzu commented on rslang/src/app/shared/services/base-action.service.ts
> +  path?: string;
unused

2021-03-29 11:08 UTC, Nikitzu commented on rslang/src/app/shared/services/base-data.service.ts
> +  path?: string;
unused

2021-03-29 11:22 UTC, Nikitzu approved these changes

2021-03-29 11:56 UTC, merged