[Ebook Words] Create list (issue #11)
whattablackhole/rslang-archive- pull request #37
Opened 2021-03-27 06:05 UTC by kastrubait

Implemented:
- [x] the home page of the tutorial (issue https://github.com/whattablackhole/rslang/issues/35)
- [x] collections page (issue https://github.com/whattablackhole/rslang/issues/36)
- [ ] Create list of words
- [x] Add rule airbnb-base, stylelint, husky,
- [x] Eslint bugs fixed

#### With the current eslint settings, it is not possible to fulfill the component naming convention!!

2021-03-27 10:11 UTC, whattablackhole commented on rslang/src/app/ebook/models/wordStudy.model.ts
> +export interface WordStady extends Word {
wrong name

2021-03-27 10:15 UTC, whattablackhole commented on rslang/src/app/ebook/ebook.module.ts
> +import { EbookHomeComponent } from './components/ebook-page/ebook-home.component';
remove  name part 'Component' from the word, add eslint rule if needed

2021-03-27 10:19 UTC, kastrubait commented on rslang/src/app/ebook/ebook.module.ts
> +import { EbookHomeComponent } from './components/ebook-page/ebook-home.component';
The component was named so in the develop, so I thought it necessary to leave it that way))

2021-03-28 07:42 UTC, Nikitzu requested changes

2021-03-28 07:42 UTC, Nikitzu commented on rslang/src/app/ebook/components/collections/collections.component.html
> +  <ng-container *ngIf="collections.length > 0; else isEmptyBlock">
can be simplified to "collections.length"

2021-03-28 07:42 UTC, Nikitzu commented on rslang/src/app/ebook/components/collections/collections.component.html
> +    <div  class="collections-container--empty">
unnecessary space

2021-03-28 07:42 UTC, Nikitzu commented on rslang/src/app/ebook/components/collections/collections.component.spec.ts
> +    expect(component).toBeTruthy();
Maybe toBeDefined?

2021-03-28 07:42 UTC, Nikitzu commented on rslang/src/app/ebook/components/collections/collections.component.ts
> +import { Collection } from '../../models/collection.models';
file should be named collection.model as soon as you should have only ONE model in it

2021-03-28 07:42 UTC, Nikitzu commented on rslang/src/app/ebook/components/collections/collections.component.ts
> +    console.log(this.collections);
?

2021-03-28 07:42 UTC, Nikitzu commented on rslang/src/app/ebook/components/ebook-page/ebook-home.component.ts
> +    console.log(this.collections);
?

2021-03-28 07:42 UTC, Nikitzu commented on rslang/src/app/ebook/components/ebook-page/ebook-home.component.ts
> +  wordSubscription!: Subscription;
unused property

2021-03-28 07:42 UTC, Nikitzu commented on rslang/src/app/ebook/components/ebook-page/ebook-home.component.ts
> +  group = 0;
unused

2021-03-28 07:42 UTC, Nikitzu commented on rslang/src/app/ebook/components/list-words/list-words.component.spec.ts
> +    expect(component).toBeTruthy();
defined?

2021-03-28 07:42 UTC, Nikitzu commented on rslang/src/app/ebook/ebook.module.ts
> +import { EbookHomeComponent } from './components/ebook-page/ebook-home.component';
No it is not

2021-03-28 07:42 UTC, Nikitzu commented on rslang/src/app/ebook/models/collection.models.ts
> +export interface Collection {
Unclear name of the model. Collection? Collection of what?

2021-03-28 07:42 UTC, Nikitzu commented on rslang/src/app/ebook/models/wordStudy.model.ts
> +export interface WordStady extends Word {
agree

2021-03-28 07:42 UTC, Nikitzu commented on rslang/src/app/ebook/models/wordStudy.model.ts
> +  };
toStudy, usedInSprint, usedInSavannah, usedInAudiocall - should have their own models. All objects should have models if they are custom typed. By the way three of four properties will have the same type that should be named somehow with respect of that fact.

2021-03-28 07:42 UTC, Nikitzu commented on rslang/src/app/shared/shared.module.ts
> +  providers: [],
Empty?

2021-03-28 07:42 UTC, Nikitzu commented on rslang/src/app/shared/models/options.model.ts
> +  params?: HttpParams | { [param: string]: string | string[] };
headers and params - should be typed instead of { [header: string]: string | string[] }

2021-03-28 08:28 UTC, kastrubait commented on rslang/src/app/ebook/models/wordStudy.model.ts
> +  };
fix

2021-03-28 08:46 UTC, kastrubait commented on rslang/src/app/ebook/components/collections/collections.component.ts
> +import { Collection } from '../../models/collection.models';
fix

2021-03-28 11:39 UTC, Nikitzu requested changes

2021-03-28 11:39 UTC, Nikitzu commented on rslang/src/app/ebook/models/word-statistics.model.ts
> +}
One file - one interface

2021-03-28 16:30 UTC, Anntol commented on rslang/src/app/shared/constants/api-url.ts
> +const BASE_URL = 'https://afternoon-falls-25894.herokuapp.com';
Please use https://rslang-team4-whattablackhole.netlify.app/

2021-03-28 16:33 UTC, Nikitzu requested changes

2021-03-28 16:33 UTC, Nikitzu commented on rslang/src/app/ebook/components/collections/collections.component.ts
> +export class Collections {
Can we define what collection do we mean?

2021-03-28 16:33 UTC, Nikitzu commented on rslang/src/app/ebook/components/ebook-page/ebook-home.component.ts
> +  collections: CollectionWords[] = CONFIG_EBOOK.collections;
WordsCollection?

2021-03-28 16:33 UTC, Nikitzu commented on rslang/src/app/ebook/components/list-words/list-words.component.ts
> +  @Input() wordsList!: Word[];
can be just words as Interface

2021-03-28 16:33 UTC, Nikitzu commented on rslang/src/app/ebook/models/collection-words.model.ts
> +export interface CollectionWords {
WordsCollection

2021-03-28 16:33 UTC, Nikitzu commented on rslang/src/app/ebook/models/word-statistics.model.ts
> +interface Progress {
Progress of what? All progress or for some game?

2021-03-28 16:33 UTC, Nikitzu commented on rslang/src/app/ebook/models/word-statistics.model.ts
> +interface Result {
Result of what? All result or for some game?

2021-03-28 16:39 UTC, kastrubait commented on rslang/src/app/ebook/models/word-statistics.model.ts
> +interface Progress {
Structure contains data for each game, so all progres.

2021-03-28 16:52 UTC, kastrubait commented on rslang/src/app/ebook/models/word-statistics.model.ts
> +interface Progress {
And track progress for a word!

2021-03-28 16:53 UTC, kastrubait commented on rslang/src/app/ebook/models/word-statistics.model.ts
> +interface Result {
result is the result of learning one word.

2021-03-28 16:54 UTC, kastrubait commented on rslang/src/app/shared/constants/api-url.ts
> +const BASE_URL = 'https://afternoon-falls-25894.herokuapp.com';
fix

2021-03-28 16:56 UTC, kastrubait commented on rslang/src/app/ebook/components/collections/collections.component.ts
> +export class Collections {
This is a list of all collections

2021-03-28 16:56 UTC, kastrubait commented on rslang/src/app/ebook/components/ebook-page/ebook-home.component.ts
> +  collections: CollectionWords[] = CONFIG_EBOOK.collections;
fix

2021-03-28 16:56 UTC, kastrubait commented on rslang/src/app/ebook/models/collection-words.model.ts
> +export interface CollectionWords {
fix

2021-03-28 17:28 UTC, kastrubait commented on rslang/src/app/ebook/models/word-statistics.model.ts
> +}
ok

2021-03-29 09:32 UTC, Nikitzu requested changes

2021-03-29 09:32 UTC, Nikitzu commented on rslang/src/app/ebook/components/collections/words-collections.component.ts
> +  @Output() group: EventEmitter<number> = new EventEmitter<number>();
Name like an event. setGroup for example.

2021-03-29 09:32 UTC, Nikitzu commented on rslang/src/app/ebook/components/list-words/list-words.component.ts
> +export class ListWords {
WordsList?

2021-03-29 11:06 UTC, Nikitzu approved these changes

2021-03-29 11:06 UTC, merged