[App]  Navigation
whattablackhole/rslang-archive- pull request #44
Opened 2021-03-27 20:42 UTC by whattablackhole

2021-03-27 20:51 UTC, Anntol commented on rslang/src/app/navigation/dot-menu/dot-menu.component.ts
> +  styleUrls: ['./dot-menu.component.scss'],
Do we need empty style file?

2021-03-28 07:45 UTC, Nikitzu requested changes

2021-03-28 07:45 UTC, Nikitzu commented on rslang/src/app/navigation/dot-menu/dot-menu.component.html
> +      <span> Статистика</span>
space

2021-03-28 07:45 UTC, Nikitzu commented on rslang/src/app/navigation/dot-menu/dot-menu.component.ts
> +  styleUrls: ['./dot-menu.component.scss'],
No

2021-03-28 07:45 UTC, Nikitzu commented on rslang/src/app/statistics/components/statistics-page/statistics-page.component.ts
> +export class StatisticsPageComponent {}
Why all component classes in this PR named with word COMPONENT?

2021-03-29 10:55 UTC, Nikitzu approved these changes

2021-03-29 11:57 UTC, Nikitzu approved these changes

2021-03-29 12:51 UTC, merged