refactor: change code shape
whattablackhole/rslang-archive- pull request #49
Opened 2021-03-29 16:18 UTC by whattablackhole

2021-03-29 16:34 UTC, Anntol commented on rslang/src/app/shared/services/words-data.service.ts
> +  // eslint-disable-next-line @typescript-eslint/no-useless-constructor
We do not need this constructor unless we have specific code for this service. It will do parent's by default.

2021-03-29 16:43 UTC, whattablackhole commented on rslang/src/app/shared/services/words-data.service.ts
> +  // eslint-disable-next-line @typescript-eslint/no-useless-constructor
I'm sure it will not

2021-03-30 07:55 UTC, Nikitzu requested changes

2021-03-30 07:55 UTC, Nikitzu commented on rslang/src/app/shared/models/callback-object.model.ts
> +  onSuccess?: (result: unknown) => void;
unknown???

2021-03-30 07:55 UTC, Nikitzu commented on rslang/src/app/shared/models/http-options.model.ts
> +  body?: unknown;
?

2021-03-30 07:55 UTC, Nikitzu commented on rslang/src/app/shared/services/base-action.service.ts
> +      (value: unknown) => {
?

2021-03-30 07:55 UTC, Nikitzu commented on rslang/src/app/shared/services/words-data.service.ts
> +  // eslint-disable-next-line @typescript-eslint/no-useless-constructor
It wont. All child should have super() call

2021-03-30 12:01 UTC, whattablackhole commented on rslang/src/app/shared/models/http-options.model.ts
> +  body?: unknown;
may i leave it ?

2021-03-30 12:14 UTC, Nikitzu approved these changes

2021-03-30 12:20 UTC, merged