[Ebook settings] Create settings ( issue #14)
whattablackhole/rslang-archive- pull request #53
Opened 2021-03-31 13:53 UTC by kastrubait

- [x] add ebookSettings component
- [x] initialization service ebookSettings
- [x] add styling to the component
- [ ] configure routing

2021-03-31 13:57 UTC, Anntol commented on rslang/src/app/shared/models/optionss.model.ts
> +export interface Options {
typo (2 s) in filename?

2021-03-31 14:00 UTC, kastrubait commented on rslang/src/app/shared/models/optionss.model.ts
> +export interface Options {
This is not my file)) Why do you write comments on someone else's work?

2021-03-31 14:02 UTC, Anntol commented on rslang/src/app/shared/models/optionss.model.ts
> +export interface Options {
It is shown as part of "Files changes" for this PR

2021-03-31 15:06 UTC, Nikitzu requested changes

2021-03-31 15:06 UTC, Nikitzu commented on rslang/src/app/ebook/components/ebook-home/ebook-home.component.ts
> +          if (events.type === 'set' && events.key === 'bookSettings') {
Can we use enums for event type and key?

2021-03-31 15:06 UTC, Nikitzu commented on rslang/src/app/ebook/components/ebook-settings/ebook-settings.component.ts
> +    if (settingsForm.invalid) {
can we disable submit is form is invalid in order not to check it here?

2021-03-31 15:06 UTC, Nikitzu commented on rslang/src/app/ebook/components/words-collections/words-collections.component.spec.ts
> +    comp.groupIdChanged.subscribe(selectedWordsCollection => expect(selectedWordsCollection).toContain(wordsCollections))
please avoid using expect in async actions. It is not a good way of testing

2021-03-31 15:06 UTC, Nikitzu commented on rslang/src/app/ebook/services/ebook-settings-init.service.ts
> +  Init(): Promise<void> {
Why capital letter for method name?

2021-03-31 15:06 UTC, Nikitzu commented on rslang/src/app/ebook/services/ebook-settings-init.service.ts
> +export class EbookSettingsInitService {
What does it mean init service? all service are inited

2021-03-31 15:06 UTC, Nikitzu commented on rslang/src/app/ebook/services/ebook-settings-init.service.ts
> +    return new Promise<void>((resolve) => {
Please if you want async use observables

2021-03-31 15:06 UTC, Nikitzu commented on rslang/src/app/shared/models/optionss.model.ts
> +export interface Options {
As soon as file is changed here. If you made mistake in branches so it is not a problem of reviewer

2021-04-01 08:21 UTC, whattablackhole commented on rslang/src/app/ebook/components/ebook-home/ebook-home.component.ts
> +  changeSelectedBookSetting(bookSettingsChanged: UserBookSettings): void {
don't mix 'ebook' and 'book' fixture naming

2021-04-01 14:09 UTC, kastrubait commented on rslang/src/app/shared/models/optionss.model.ts
> +export interface Options {
fix

2021-04-01 15:04 UTC, kastrubait commented on rslang/src/app/ebook/services/ebook-settings-init.service.ts
> +  Init(): Promise<void> {
fix

2021-04-01 16:01 UTC, kastrubait commented on rslang/src/app/ebook/components/ebook-home/ebook-home.component.ts
> +          if (events.type === 'set' && events.key === 'bookSettings') {
I think it's possible

2021-04-01 17:26 UTC, kastrubait commented on rslang/src/app/ebook/components/words-collections/words-collections.component.spec.ts
> +    comp.groupIdChanged.subscribe(selectedWordsCollection => expect(selectedWordsCollection).toContain(wordsCollections))
And what do they use if not expect ??

2021-04-01 18:02 UTC, kastrubait commented on rslang/src/app/ebook/components/ebook-home/ebook-home.component.ts
> +  changeSelectedBookSetting(bookSettingsChanged: UserBookSettings): void {
fix

2021-04-02 03:09 UTC, kastrubait commented on rslang/src/app/ebook/services/ebook-settings-init.service.ts
> +export class EbookSettingsInitService {
I planned, when opening the ebook, to initialize the user settings, if the user is not registered, then read the setting from the localstorage or config file.

But Correcting comments- I got even more bugs and got stuck (( I need help

2021-04-02 13:26 UTC, Nikitzu requested changes

2021-04-02 13:26 UTC, Nikitzu commented on rslang/src/app/ebook/components/words-collections/words-collections.component.spec.ts
> +    comp.groupIdChanged.subscribe(selectedWordsCollection => expect(selectedWordsCollection).toContain(wordsCollections))
You need to write test in way that will not check async action. For example you can check not the value but the call of the subscribe with the help of spy function

2021-04-02 13:26 UTC, Nikitzu commented on rslang/src/app/shared/models/change-storage-type.model.ts
> +  set = 'set',
capital letter.

2021-04-02 13:26 UTC, Nikitzu commented on rslang/src/app/shared/models/local-storage-keys.model.ts
> +  ebookSettings = 'ebookSettings',
capital letter

2021-04-02 13:26 UTC, Nikitzu commented on rslang/src/app/ebook/components/ebook-home/ebook-home.component.ts
> +  ebookSettingsChanges$ = this.localStorageService.changes$;
for what do we need this var? cant we doo all the same without it?

2021-04-02 13:26 UTC, Nikitzu commented on rslang/src/app/ebook/components/words-collections/words-collections.component.html
> +        *ngFor="let collection of wordsCollections; index as item"
maybe index as i?

2021-04-02 13:26 UTC, Nikitzu commented on rslang/src/app/ebook/ebook.module.ts
> +export function initializeEbookSettings(ebookSettingsInitService: EbookSettingsInitService) {
What? Cant we use service for settings?

2021-04-02 13:26 UTC, Nikitzu commented on rslang/src/app/ebook/services/ebook-settings-init.service.ts
> +  providedIn: 'root',
Why this service is root?

2021-04-02 13:26 UTC, Nikitzu commented on rslang/src/app/ebook/services/ebook-settings-init.service.ts
> +export class EbookSettingsInitService {
Your plans don't matter. We should not use INIT in service name as soon as it is too missleading

2021-04-02 13:26 UTC, Nikitzu commented on rslang/src/app/ebook/services/ebook-settings-init.service.ts
> +    if (data === null) {
maybe if !data?

2021-04-03 12:51 UTC, kastrubait commented on rslang/src/app/ebook/components/ebook-settings/ebook-settings.component.ts
> +    if (settingsForm.invalid) {
checking the valid before submitting the form

2021-04-03 12:53 UTC, kastrubait commented on rslang/src/app/ebook/services/ebook-settings-init.service.ts
> +export class EbookSettingsInitService {
changed the naming of the service

2021-04-03 14:37 UTC, kastrubait commented on rslang/src/app/ebook/services/ebook-settings-init.service.ts
> +    return new Promise<void>((resolve) => {
EbookSettingsInitService is temporarily unused

2021-04-03 14:46 UTC, kastrubait commented on rslang/src/app/shared/models/change-storage-type.model.ts
> +  set = 'set',
fix

2021-04-03 14:46 UTC, kastrubait commented on rslang/src/app/shared/models/local-storage-keys.model.ts
> +  ebookSettings = 'ebookSettings',
fix

2021-04-03 14:48 UTC, kastrubait commented on rslang/src/app/ebook/components/words-collections/words-collections.component.html
> +        *ngFor="let collection of wordsCollections; index as item"
So be it

2021-04-03 14:50 UTC, kastrubait commented on rslang/src/app/ebook/services/ebook-settings-init.service.ts
> +  providedIn: 'root',
root means globally. Am I wrong again?

2021-04-03 14:51 UTC, kastrubait commented on rslang/src/app/ebook/services/ebook-settings-init.service.ts
> +    if (data === null) {
Yes, that's better!!

2021-04-05 16:51 UTC, Nikitzu requested changes

2021-04-05 16:51 UTC, Nikitzu commented on rslang/src/app/ebook/components/ebook-home/ebook-home.component.ts
> +  ebookSettingsSubscription = new Subscription();
Why we create new Subscription if in OnInit we have another one?

2021-04-05 16:51 UTC, Nikitzu commented on rslang/src/app/ebook/components/ebook-home/ebook-home.component.ts
> +    this.ebookSettingsService.firstLoadAndSet();
Method violates Single responsibility princip

2021-04-05 16:51 UTC, Nikitzu commented on rslang/src/app/ebook/components/ebook-settings/ebook-settings.component.html
> +      <input type="text" id="username" placeholder="Name" />
Why not mat-form field?

2021-04-05 18:06 UTC, kastrubait commented on rslang/src/app/ebook/components/ebook-settings/ebook-settings.component.html
> +      <input type="text" id="username" placeholder="Name" />
If it is so fundamentally I can change

2021-04-06 01:34 UTC, kastrubait commented on rslang/src/app/ebook/components/ebook-home/ebook-home.component.ts
> +    this.ebookSettingsService.firstLoadAndSet();
oh yeah .. fixed, thanks

2021-04-06 07:00 UTC, Nikitzu requested changes

2021-04-06 07:00 UTC, Nikitzu commented on rslang/src/app/shared/services/local-storage.service.ts
> +    return !!(this.storage[key] || '');
What do we use this method for? Why we dont check keys via hasOwnProperty?

2021-04-06 07:00 UTC, Nikitzu commented on rslang/src/app/ebook/services/ebook-settings.service.ts
> +  firstLoad(): void {
maybe just load?

2021-04-06 07:00 UTC, Nikitzu commented on rslang/src/app/ebook/services/ebook-settings.service.ts
> +    if (this.localStorageService.isKey(LocalStorageKey.EbookSettings)) {
why we have method called load but actually it doesn't load anything. It simply checks local storage.

2021-04-06 16:47 UTC, kastrubait commented on rslang/src/app/ebook/components/ebook-home/ebook-home.component.ts
> +  ebookSettingsSubscription = new Subscription();
fix

2021-04-06 16:49 UTC, kastrubait commented on rslang/src/app/ebook/components/ebook-home/ebook-home.component.ts
> +  ebookSettingsChanges$ = this.localStorageService.changes$;
yes, we can. Fix

2021-04-06 16:52 UTC, kastrubait commented on rslang/src/app/shared/services/local-storage.service.ts
> +    return !!(this.storage[key] || '');
Ыo be it, thanks for the hint

2021-04-06 16:52 UTC, kastrubait commented on rslang/src/app/ebook/services/ebook-settings.service.ts
> +  firstLoad(): void {
ok

2021-04-07 01:38 UTC, kastrubait commented on rslang/src/app/ebook/services/ebook-settings.service.ts
> +    if (this.localStorageService.isKey(LocalStorageKey.EbookSettings)) {
Add service for receiving data settings from the server,

2021-04-08 07:42 UTC, Nikitzu requested changes

2021-04-08 07:42 UTC, Nikitzu commented on rslang/src/app/ebook/components/ebook-home/ebook-home.component.ts
> +  ebookSettingsChanges$ = this.localStorageService.changes$;
No

2021-04-08 07:42 UTC, Nikitzu commented on rslang/src/app/ebook/components/ebook-settings/ebook-settings.component.html
> +      <input type="text" id="username" placeholder="Name" />
Yes please change

2021-04-08 07:42 UTC, Nikitzu commented on rslang/src/app/ebook/components/words-collections/words-collections.component.html
> +        *ngFor="let collection of wordsCollections; index as item"
index is not an item

2021-04-08 07:42 UTC, Nikitzu commented on rslang/src/app/ebook/services/ebook-settings.service.ts
> +  ) { this.globalSettings = this.settingsService.data$; }
unnecessary variable

2021-04-08 15:24 UTC, Nikitzu requested changes

2021-04-08 15:24 UTC, Nikitzu commented on rslang/src/app/ebook/services/ebook-settings.service.ts
> +    this.setDefaultSettings(Object.prototype.hasOwnProperty.call(localStorage, LocalStorageKey.EbookSettings));
```suggestion
    if (!localStorage.hasOwnProperty(LocalStorageKey.EbookSettings)) {
       this.setDefaultSettings(localStorage.hasOwnProperty(LocalStorageKey.EbookSettings));
    }
```

2021-04-09 07:08 UTC, Nikitzu requested changes

2021-04-09 07:08 UTC, Nikitzu commented on rslang/.eslintrc.json
> +        "no-prototype-builtins": "warn",
Why warn?

2021-04-09 07:08 UTC, Nikitzu commented on rslang/src/app/ebook/components/ebook-settings/ebook-settings.component.html
> +        <input matInput id="username" value="User name" />
Where is the validation?

2021-04-09 07:08 UTC, Nikitzu commented on rslang/src/app/ebook/services/ebook-settings.service.ts
> +      const defaultSettings = EBOOK_SETTINGS;
Why here we have four spaces and int the above method only two? What is the right style?

2021-04-09 08:01 UTC, kastrubait commented on rslang/.eslintrc.json
> +        "no-prototype-builtins": "warn",
Maybe "off", but I think this is a bad idea

2021-04-09 08:01 UTC, kastrubait commented on rslang/src/app/ebook/components/ebook-settings/ebook-settings.component.html
> +        <input matInput id="username" value="User name" />
add

2021-04-09 08:03 UTC, kastrubait commented on rslang/src/app/ebook/services/ebook-settings.service.ts
> +      const defaultSettings = EBOOK_SETTINGS;
I didn't really understand about spaces, There should be two!

2021-04-09 08:16 UTC, Nikitzu requested changes

2021-04-09 08:16 UTC, Nikitzu commented on rslang/src/app/ebook/components/ebook-home/ebook-home.component.ts
> +  changeDetection: ChangeDetectionStrategy.OnPush,
For what?

2021-04-09 08:16 UTC, Nikitzu commented on rslang/src/app/ebook/components/ebook-settings/ebook-settings.component.html
> +        {{ itembtn.label }}
What happened with alignment?

2021-04-09 08:17 UTC, Nikitzu commented on rslang/src/app/ebook/services/ebook-settings.service.ts
> +      const defaultSettings = EBOOK_SETTINGS;
But there are four.

2021-04-09 08:17 UTC, Nikitzu commented on rslang/.eslintrc.json
> +        "no-prototype-builtins": "warn",
Why?

2021-04-10 01:24 UTC, kastrubait commented on rslang/src/app/ebook/components/ebook-home/ebook-home.component.ts
> +  changeDetection: ChangeDetectionStrategy.OnPush,
fix

2021-04-10 01:24 UTC, kastrubait commented on rslang/src/app/ebook/components/ebook-settings/ebook-settings.component.html
> +        {{ itembtn.label }}
fix

2021-04-10 01:28 UTC, kastrubait commented on rslang/.eslintrc.json
> +        "no-prototype-builtins": "warn",
I believe that rules should be disabled only in exceptional cases.

2021-04-10 07:50 UTC, Nikitzu approved these changes

2021-04-10 13:10 UTC, merged