Main page + About page
whattablackhole/rslang-archive- pull request #55
Opened 2021-04-01 15:40 UTC by superpuper777

This PR for only team-review to identify gaps in the development process (only for full-screen).

2021-04-01 15:50 UTC, Nikitzu requested changes

2021-04-01 15:50 UTC, Nikitzu commented on rslang/src/app/main/team/team.html
> +            >Team Lead</mat-card-subtitle
Not good code style. return closed bracket on the previous line

2021-04-01 15:50 UTC, Nikitzu commented on rslang/src/app/main/team/team.html
> +              src="https://us.123rf.com/450wm/alexutemov/alexutemov1605/alexutemov160500383/56523661-la-felicidad-concepto-de-la-gente-la-cara-joven-hombre-de-la-barba-feliz-vector-de-la-cara-y-la-ca
we should not have such long links

2021-04-01 15:50 UTC, Nikitzu commented on rslang/src/app/main/team/team.html
> +              src="https://us.123rf.com/450wm/alexutemov/alexutemov1605/alexutemov160500383/56523661-la-felicidad-concepto-de-la-gente-la-cara-joven-hombre-de-la-barba-feliz-vector-de-la-cara-y-la-ca
same

2021-04-01 15:50 UTC, Nikitzu commented on rslang/src/app/main/team/team.html
> +              src="https://us.123rf.com/450wm/alexutemov/alexutemov1605/alexutemov160500383/56523661-la-felicidad-concepto-de-la-gente-la-cara-joven-hombre-de-la-barba-feliz-vector-de-la-cara-y-la-ca
same

2021-04-01 15:50 UTC, Nikitzu commented on rslang/src/app/main/team/team.html
> +              src="https://us.123rf.com/450wm/alexutemov/alexutemov1605/alexutemov160500383/56523661-la-felicidad-concepto-de-la-gente-la-cara-joven-hombre-de-la-barba-feliz-vector-de-la-cara-y-la-ca
same

2021-04-01 15:50 UTC, Nikitzu commented on rslang/src/app/main/team/team.html
> +                src="https://us.123rf.com/450wm/alexutemov/alexutemov1605/alexutemov160500383/56523661-la-felicidad-concepto-de-la-gente-la-cara-joven-hombre-de-la-barba-feliz-vector-de-la-cara-y-la-
same

2021-04-01 15:50 UTC, Nikitzu commented on rslang/src/app/main/team/team.html
> +                src="https://us.123rf.com/450wm/alexutemov/alexutemov1605/alexutemov160500383/56523661-la-felicidad-concepto-de-la-gente-la-cara-joven-hombre-de-la-barba-feliz-vector-de-la-cara-y-la-
same

2021-04-01 15:50 UTC, Nikitzu commented on rslang/src/app/main/team/team.scss
> +.main__our_team {
why __ and then _?

2021-04-01 15:50 UTC, Nikitzu commented on rslang/src/app/material/material.module.ts
> +import { MatCardModule } from '@angular/material/card';
remove. module will be deprecated

2021-04-01 15:50 UTC, Nikitzu commented on rslang/src/app/material/material.module.ts
> +  ],
same

2021-04-02 15:57 UTC, coriander31415 requested changes

2021-04-02 15:57 UTC, coriander31415 commented on rslang/src/app/main/team/team.html
> +  <h3 class="main__our__team__title">OUR TEAM</h3>
Center the title, please

2021-04-02 15:57 UTC, coriander31415 commented on rslang/src/app/main/components/main-page/main-page.component.html
> +  <h3 class="main-page__advantages__title">OUR ADVANTAGES</h3>
Center the title, please

2021-04-03 18:58 UTC, whattablackhole commented
not quite responsive
![Screenshot from 2021-04-03 21-57-22](https://user-images.githubusercontent.com/59873638/113488578-b7eb8380-94c7-11eb-90d3-221166fa7f78.png)

2021-04-03 23:21 UTC, superpuper777 commented
> not quite responsive
> ![Screenshot from 2021-04-03 21-57-22](https://user-images.githubusercontent.com/59873638/113488578-b7eb8380-94c7-11eb-90d3-221166fa7f78.png)

2021-04-03 23:21 UTC, closed without merging