refactor: project structure
whattablackhole/rslang-archive- pull request #57
Opened 2021-04-03 12:19 UTC by kastrubait

2021-04-03 12:32 UTC, coriander31415 approved these changes

2021-04-03 16:51 UTC, Anntol commented on rslang/src/app/components/dot-menu/dot-menu.component.html
> +      <span>Sign In</span>
Some menu items are Upper cased, others are Lower cased. Some items are still in Russian. Why?

2021-04-03 17:29 UTC, kastrubait commented on rslang/src/app/components/dot-menu/dot-menu.component.html
> +      <span>Sign In</span>
I have not edited this menu. Just moved to fit the new structure
 In the nav-menu, I added links to the application pages, logo, translation into English. Styling will be completed after adding the main page. Therefore, it is different.

2021-04-03 18:42 UTC, whattablackhole approved these changes

2021-04-05 16:57 UTC, Nikitzu requested changes

2021-04-05 16:57 UTC, Nikitzu commented on rslang/src/app/app.module.ts
> +import { MatDialogModule } from '@angular/material/dialog';
I do not understand why we have so mane Mat modules in App.

2021-04-06 01:22 UTC, kastrubait commented on rslang/src/app/app.module.ts
> +import { MatDialogModule } from '@angular/material/dialog';
modules are imported into shared

2021-04-06 08:56 UTC, Nikitzu approved these changes

2021-04-06 09:17 UTC, merged