feat: add sprint, common components
whattablackhole/rslang-archive- pull request #58
Opened 2021-04-03 14:33 UTC by whattablackhole

Alpha version :3rd_place_medal:

2021-04-03 16:36 UTC, Anntol commented on rslang/src/app/games/services/game-core.service.ts
> +      return true;
it is better to use return (boolean condition)

2021-04-03 16:43 UTC, Anntol commented on rslang/src/app/games/sprint/components/sprint/sprint.component.ts
> +  currectStreak = 0;
misspelling for currectStreak

2021-04-03 16:46 UTC, Anntol commented on rslang/src/app/games/sprint/components/sprint/sprint.component.ts
> +}
It is better to create constants for wordslength, scorePointsLimit etc instead of hardcoding values to avoid magic numbers in code.

2021-04-05 11:21 UTC, coriander31415 commented on rslang/src/app/games/sprint/sprint-routing.module.ts
> +const routes: Routes = [{ path: '', component: Sprint }];
Let's create common routing module for all the games: 
games-routing.module.ts where we'll set all the routes for games

2021-04-05 17:14 UTC, Nikitzu requested changes

2021-04-05 17:14 UTC, Nikitzu commented on rslang/src/app/app.component.ts
> +      } else if (event instanceof NavigationError) {
We really need three else-if? In all the cases there is false. Cant we combine all this if-else into one ternary expression?

2021-04-05 17:14 UTC, Nikitzu commented on rslang/src/app/ebook/models/word-statistics.model.ts
> +// eslint-disable-next-line
???????

2021-04-05 17:14 UTC, Nikitzu commented on rslang/src/app/ebook/models/word-statistics.model.ts
> +  // toStudy: StudyProgress;
???????

2021-04-05 17:14 UTC, Nikitzu commented on rslang/src/app/games/components/finish-menu/finish-menu.component.ts
> +  @ViewChild('cnt', { static: false }) public cnt: ElementRef;
cnt? missleading name

2021-04-05 17:14 UTC, Nikitzu commented on rslang/src/app/games/components/finish-menu/finish-menu.component.ts
> +  @Input() gameCorrectPercent: number;
correctGamePercent?

2021-04-05 17:14 UTC, Nikitzu commented on rslang/src/app/games/components/finish-menu/finish-menu.component.ts
> +  runAnimation(): void {
can and should be private

2021-04-05 17:14 UTC, Nikitzu commented on rslang/src/app/games/components/screen-size-changer/screen-size-changer.component.html
> +  </button>
can be done with one button, one method and switching of the icon only

2021-04-05 17:14 UTC, Nikitzu commented on rslang/src/app/games/components/screen-size-changer/screen-size-changer.component.ts
> +      void this.screen.requestFullscreen(); // eslint-disable-line no-void
???

2021-04-05 17:14 UTC, Nikitzu commented on rslang/src/app/games/components/screen-size-changer/screen-size-changer.component.ts
> +      void document.exitFullscreen(); // eslint-disable-line no-void
???

2021-04-05 17:14 UTC, Nikitzu commented on rslang/src/app/games/components/start-animation/start-animation.component.html
> +<div *ngIf="isGameStarted" class="start">
What will be shown if ngIf will be false?

2021-04-05 17:14 UTC, Nikitzu commented on rslang/src/app/games/services/game-core.service.ts
> +  providedIn: 'root',
Do we really need it in root?

2021-04-05 17:14 UTC, Nikitzu commented on rslang/src/app/games/services/game-core.service.ts
> +      if (pagesArray.length === 0) {
can be !!pagesArray.length

2021-04-05 17:14 UTC, Nikitzu commented on rslang/src/app/games/services/game-core.service.ts
> +      if (word.isRemove === true || word.knowledgeDegree >= 3) {
What??? === true???? Why no just word.isRemove??

2021-04-05 17:14 UTC, Nikitzu commented on rslang/src/app/games/services/game-core.service.ts
> +      return true;
Do not understand this comment, sorry.

2021-04-05 17:14 UTC, Nikitzu commented on rslang/src/app/games/services/game-core.service.ts
> +      return true;
all this runction can be simplified to 'return word.isRemove || word.knowledgeDegree >= 3'

2021-04-05 17:14 UTC, Nikitzu commented on rslang/src/app/games/sprint/components/sprint/sprint.component.html
> +    <div *ngIf="gameLevel > 3" class="game__img-lvl game__img-lvl_four"></div>
cant we use ngClass here?

2021-04-05 17:14 UTC, Nikitzu commented on rslang/src/app/games/sprint/components/sprint/sprint.component.ts
> +      return false;
can be simplified to return 'item.id === this.word.id'

2021-04-05 17:14 UTC, Nikitzu commented on rslang/src/app/games/sprint/components/sprint/sprint.component.ts
> +    if (answer === true) {
??? just answer

2021-04-05 17:14 UTC, Nikitzu commented on rslang/src/app/games/sprint/components/sprint/sprint.component.ts
> +    if (answer === true) {
same

2021-04-05 17:14 UTC, Nikitzu commented on rslang/src/app/games/sprint/components/sprint/sprint.component.ts
> +    if (result === true) {
result

2021-04-05 17:14 UTC, Nikitzu commented on rslang/src/app/games/sprint/components/sprint/sprint.component.ts
> +    } else if (result === false) {
!result. but actually we dont need this if. can be just else.

2021-04-05 17:14 UTC, Nikitzu commented on rslang/src/app/shared/models/word-statistics.model.ts
> +  // toStudy: StudyProgress;
?

2021-04-06 08:23 UTC, whattablackhole commented on rslang/src/app/games/components/start-animation/start-animation.component.html
> +<div *ngIf="isGameStarted" class="start">
nothing, it's similar to a spinner

2021-04-08 07:50 UTC, Nikitzu requested changes

2021-04-08 07:50 UTC, Nikitzu commented on rslang/src/app/app.component.ts
> +        event instanceof NavigationEnd || // eslint-disable-line operator-linebreak
Lets make ts lint rule to work here

2021-04-09 11:16 UTC, coriander31415 commented
Move MatProgressSpinnerModule to the SharedModule

2021-04-09 13:34 UTC, Nikitzu requested changes

2021-04-09 13:34 UTC, Nikitzu commented on rslang/src/app/games/audiocall/components/audiocall/audiocall.component.ts
> +  userWords: Observable<WordWithStatistics[]>;
We really need additional properties for observables? Can't we use public properties from services?

2021-04-09 13:34 UTC, Nikitzu commented on rslang/src/app/games/audiocall/components/audiocall/audiocall.component.ts
> +    this.userWords = this.userAggregatedWordsService.data$;
just to avoid this assignment

2021-04-10 08:20 UTC, Nikitzu requested changes

2021-04-10 08:20 UTC, Nikitzu commented on rslang/src/app/app.component.ts
> +      }
please refactor this if-else

2021-04-11 06:29 UTC, Nikitzu approved these changes

2021-04-11 09:03 UTC, merged