Statistics Page
whattablackhole/rslang-archive- pull request #59
Opened 2021-04-03 17:19 UTC by EvilKami7

Statistic components and services

2021-04-05 17:20 UTC, Nikitzu requested changes

2021-04-05 17:20 UTC, Nikitzu commented on rslang/src/app/statistics/components/long-term-statistic/long-term-statistic.component.ts
> +  public dates: string[];
do we wright public word?

2021-04-05 17:20 UTC, Nikitzu commented on rslang/src/app/statistics/components/long-term-statistic/long-term-statistic.component.ts
> +  // @ts-ignore
?

2021-04-05 17:20 UTC, Nikitzu commented on rslang/src/app/statistics/components/long-term-statistic/long-term-statistic.component.ts
> +  // @ts-ignore
?

2021-04-05 17:20 UTC, Nikitzu commented on rslang/src/app/statistics/components/long-term-statistic/long-term-statistic.component.ts
> +  // @ts-ignore
?

2021-04-05 17:20 UTC, Nikitzu commented on rslang/src/app/statistics/components/statistics-page/statistics-page.component.html
> +    <mat-tab *ngFor="let statistic of statisticsList; let index = index" [label]="statistic.date.toLocaleDateString()">
do we need index?

2021-04-05 17:20 UTC, Nikitzu commented on rslang/src/app/statistics/models/game-session.model.ts
> +  game_id?: string;
Is it possible that session will be without id?

2021-04-05 17:20 UTC, Nikitzu commented on rslang/src/app/statistics/models/game-session.model.ts
> +interface WordId {
What do we use this interface for? Ans why?

2021-04-05 17:20 UTC, Nikitzu commented on rslang/src/app/statistics/services/games-aggregation.service.ts
> +  providedIn: 'root',
Do we need it in root?

2021-04-05 17:20 UTC, Nikitzu commented on rslang/src/app/statistics/services/statistic-calculation.service.ts
> +  providedIn: 'root',
same

2021-04-05 17:20 UTC, Nikitzu commented on rslang/src/app/statistics/services/statistic-calculation.service.ts
> +  getWinrate(gamesSession: GameSession): number {
getWinRate?

2021-04-07 15:52 UTC, EvilKami7 commented on rslang/src/app/statistics/models/game-session.model.ts
> +interface WordId {
We use this interface because for calculating game statistics from game sessions we don't need all word info. Only Id.
And it's temporary interfaces because I'll use interface which used in games.

2021-04-08 07:37 UTC, Nikitzu requested changes

2021-04-08 07:37 UTC, Nikitzu commented on rslang/src/app/statistics/components/long-term-statistic/long-term-statistic.component.ts
> +  public lineChartData: ChartDataSets[];
no public

2021-04-08 09:07 UTC, Anntol approved these changes
It is not adapted for small screens.

2021-04-15 12:02 UTC, Nikitzu approved these changes

2021-04-15 12:23 UTC, merged