Main + Team pages
whattablackhole/rslang-archive- pull request #60
Opened 2021-04-03 23:31 UTC by superpuper777

2021-04-05 17:22 UTC, Nikitzu requested changes

2021-04-05 17:22 UTC, Nikitzu commented on rslang/src/app/navigation/navigation.module.ts
> +    MatButtonModule,
not here

2021-04-07 08:42 UTC, Nikitzu approved these changes

2021-04-07 08:42 UTC, Nikitzu commented on rslang/src/app/components/main/main.html
> +          <h3 class="main__our__team__title">Click to show our team</h3>
h3 with text click? And where is the click itself?

2021-04-07 08:43 UTC, Nikitzu requested changes
One comment more

2021-04-07 08:51 UTC, superpuper777 commented on rslang/src/app/components/main/main.html
> +          <h3 class="main__our__team__title">Click to show our team</h3>
You need to click on the expansion panel to open it.

2021-04-08 07:33 UTC, Nikitzu approved these changes

2021-04-08 08:51 UTC, Anntol approved these changes

2021-04-08 14:23 UTC, merged