[Ebook] Ebook words list
whattablackhole/rslang-archive- pull request #63
Opened 2021-04-10 18:12 UTC by kastrubait

2021-04-11 06:29 UTC, Nikitzu requested changes

2021-04-11 06:29 UTC, Nikitzu commented on rslang/src/app/auth/components/login/login.component.html
> +          <div *ngIf="emailInput && emailInput.invalid && (emailInput.dirty || emailInput.touched)">
I thnik we can use only mat-error without this div

2021-04-11 06:29 UTC, Nikitzu commented on rslang/src/app/ebook/components/ebook-header/ebook-header.component.ts
> +    this.pageNoChanged.emit(pageNo);
better pageChanged

2021-04-11 06:29 UTC, Nikitzu commented on rslang/src/app/ebook/components/ebook-home/ebook-home.component.ts
> +    this.userBookSettings.currentState.page = pageNoChanged;
same

2021-04-11 06:29 UTC, Nikitzu commented on rslang/src/app/ebook/components/words-list/words-list.component.html
> +  <ng-container *ngIf="words.length > 0; else isEmptyCart" class="words-conteiner__list">
!!words.length

2021-04-11 06:29 UTC, Nikitzu commented on rslang/src/app/ebook/components/words-list/words-list.component.ts
> +  set subscription(sb: Subscription) { this.subscriptions.push(sb); }
why there is no unsubscribe?

2021-04-11 06:29 UTC, Nikitzu commented on rslang/src/app/ebook/directives/pagination.directive.ts
> +    return this.pageNo === 1;
pageNumber

2021-04-11 06:29 UTC, Nikitzu commented on rslang/src/app/ebook/directives/pagination.directive.ts
> +    return this.pageNo === this.totalPages;
same

2021-04-11 06:29 UTC, Nikitzu commented on rslang/src/app/shared/services/words-data.service.ts
> +    this.data$.subscribe((words: Word[]) => {
why dataService is subscribed to its own data stream??

2021-04-12 02:58 UTC, kastrubait commented on rslang/src/app/ebook/directives/pagination.directive.ts
> +    return this.pageNo === 1;
fix

2021-04-12 02:58 UTC, kastrubait commented on rslang/src/app/ebook/directives/pagination.directive.ts
> +    return this.pageNo === this.totalPages;
fix

2021-04-12 09:49 UTC, kastrubait commented on rslang/src/app/ebook/components/ebook-header/ebook-header.component.ts
> +    this.pageNoChanged.emit(pageNo);
fix

2021-04-12 09:50 UTC, kastrubait commented on rslang/src/app/ebook/components/words-list/words-list.component.html
> +  <ng-container *ngIf="words.length > 0; else isEmptyCart" class="words-conteiner__list">
fix

2021-04-13 10:50 UTC, Nikitzu requested changes

2021-04-13 10:50 UTC, Nikitzu commented on rslang/src/app/ebook/components/ebook-header/ebook-header.component.html
> +        <button (click)="pagination.first()" [disabled]="pagination.isFirst"><<</button>
what is pagination - I dont see such property in ts

2021-04-13 10:50 UTC, Nikitzu commented on rslang/src/app/ebook/components/word-item/word-item.component.ts
> +  turnOverItem(): string {
We really need a method for this static string?

2021-04-13 10:50 UTC, Nikitzu commented on rslang/src/app/ebook/components/words-list/words-list.component.ts
> +    this.words = [];
This whole method needs to be changed

2021-04-13 10:50 UTC, Nikitzu commented on rslang/src/app/ebook/components/words-list/words-list.component.ts
> +  indexWord(wordId: string): number {
wordIndex

2021-04-13 10:50 UTC, Nikitzu commented on rslang/src/app/ebook/components/words-list/words-list.component.ts
> +  changeDifficultWord(wordDifficult: string): void {
changeWordDifficulty?

2021-04-13 10:50 UTC, Nikitzu commented on rslang/src/app/ebook/components/words-list/words-list.component.ts
> +  changeRemoveWord(wordRemove: string): void {
changeRemove? so change or remove?

2021-04-13 10:50 UTC, Nikitzu commented on rslang/src/app/ebook/directives/pagination.directive.ts
> +  first(): void {
Why we need methoid for such action? Cant we call setPage(1) from page?

2021-04-13 10:50 UTC, Nikitzu commented on rslang/src/app/ebook/directives/pagination.directive.ts
> +    this.setPage(this.totalPages);
same here

2021-04-13 10:50 UTC, Nikitzu commented on rslang/src/app/ebook/directives/pagination.directive.ts
> +  private onpageNumberInput() {
onPageNumberInput

2021-04-13 10:50 UTC, Nikitzu commented on rslang/src/app/ebook/directives/pagination.directive.ts
> +      typeof this.pageNumber !== 'number'
isn't it always true?

2021-04-13 10:50 UTC, Nikitzu commented on rslang/src/app/shared/services/words-data.service.ts
> +    return this.data$;
all should be refactored

2021-04-14 06:37 UTC, kastrubait commented on rslang/src/app/shared/services/words-data.service.ts
> +    return this.data$;
was refactored

2021-04-14 20:17 UTC, kastrubait commented on rslang/src/app/ebook/components/words-list/words-list.component.ts
> +  indexWord(wordId: string): number {
why?

2021-04-14 20:17 UTC, kastrubait commented on rslang/src/app/ebook/components/words-list/words-list.component.ts
> +    this.words = [];
changed

2021-04-14 20:19 UTC, kastrubait commented on rslang/src/app/ebook/components/word-item/word-item.component.ts
> +  turnOverItem(): string {
Yes! This is a very important part of the idea

2021-04-14 20:20 UTC, kastrubait commented on rslang/src/app/ebook/components/ebook-header/ebook-header.component.html
> +        <button (click)="pagination.first()" [disabled]="pagination.isFirst"><<</button>
this is not a property, but a directive

2021-04-15 08:58 UTC, kastrubait commented on rslang/src/app/ebook/components/ebook-home/ebook-home.component.ts
> +    this.userBookSettings.currentState.page = pageNoChanged;
fix

2021-04-15 08:58 UTC, kastrubait commented on rslang/src/app/ebook/directives/pagination.directive.ts
> +  first(): void {
I suppose it's possible, but I want to make these corrections later. Is it possible?

2021-04-15 08:59 UTC, kastrubait commented on rslang/src/app/ebook/directives/pagination.directive.ts
> +    this.setPage(this.totalPages);
I suppose it's possible, but I want to make these corrections later. Is it possible?

2021-04-15 09:27 UTC, Nikitzu requested changes

2021-04-15 09:27 UTC, Nikitzu commented on rslang/src/app/ebook/components/word-item/word-item.component.ts
> +  turnOverItem(): string {
Explain please. This method is called by click. Why it has return? Where we return this value and why?

2021-04-15 09:27 UTC, Nikitzu commented on rslang/src/app/ebook/components/ebook-home/ebook-home.component.ts
> +    this.userBookSettings.currentState.page = pageNoChanged;
pageNoChanged

2021-04-15 09:27 UTC, Nikitzu commented on rslang/src/app/ebook/components/words-list/words-list.component.html
> +  </ng-container>
in this file for some reason all '=' signs are surrounded by spaces.

2021-04-15 09:27 UTC, Nikitzu commented on rslang/src/app/ebook/components/words-list/words-list.component.spec.ts
> +      declarations: [ WordsList ]
spaces

2021-04-15 09:27 UTC, Nikitzu commented on rslang/src/app/shared/services/user-word-action.service.ts
> +  // eslint-disable-next-line @typescript-eslint/no-useless-constructor
no such comments

2021-04-15 11:55 UTC, kastrubait commented on rslang/src/app/ebook/components/words-list/words-list.component.spec.ts
> +      declarations: [ WordsList ]
fix

2021-04-15 12:03 UTC, Nikitzu approved these changes

2021-04-15 12:13 UTC, coriander31415 approved these changes

2021-04-15 12:16 UTC, merged