Notification Bar
whattablackhole/rslang-archive- pull request #65
Opened 2021-04-12 01:04 UTC by Anntol

Show error or success messages

2021-04-12 15:39 UTC, Nikitzu requested changes

2021-04-12 15:39 UTC, Nikitzu commented on rslang/src/app/auth/services/auth-action.service.ts
> +            message = 'User is not found!';
maybe Page?

2021-04-12 15:39 UTC, Nikitzu commented on rslang/src/app/shared/components/notification/notification-bar.component.ts
> +    this.snackBar.open(message, undefined, {
undefined as a parameter??

2021-04-12 15:42 UTC, Anntol commented on rslang/src/app/auth/services/auth-action.service.ts
> +            message = 'User is not found!';
404 is returned from the backend when email is not found in db (it is user signing process)

2021-04-12 16:48 UTC, Anntol commented on rslang/src/app/shared/components/notification/notification-bar.component.ts
> +    this.snackBar.open(message, undefined, {
fixed

2021-04-14 10:38 UTC, Nikitzu requested changes

2021-04-14 10:38 UTC, Nikitzu commented on rslang/src/app/auth/services/auth-action.service.ts
> +  signinUser(req: SigninRequest, authService = this.authService, notifyService = this.notifyService): void {
Why we have services as a parameter of the method????

2021-04-14 20:25 UTC, Anntol commented on rslang/src/app/auth/services/auth-action.service.ts
> +  signinUser(req: SigninRequest, authService = this.authService, notifyService = this.notifyService): void {
fixed

2021-04-16 17:11 UTC, Nikitzu approved these changes

2021-04-16 17:13 UTC, kastrubait approved these changes

2021-04-16 17:15 UTC, merged