Savannah
whattablackhole/rslang-archive- pull request #69
Opened 2021-04-14 10:15 UTC by nofishtou

2021-04-14 11:18 UTC, Nikitzu requested changes

2021-04-14 11:18 UTC, Nikitzu commented on rslang/src/app/games/audiocall/components/audiocall/audiocall.component.html
> +          let item of sortedWords
sortedWord of sortedWords

2021-04-14 11:18 UTC, Nikitzu commented on rslang/src/app/games/savannah/components/savannah/savannah.component.html
> +    <div class="game__menu" *ngIf="!isGameStart && !isGameEnd">
*ngIf="!isGameStart" is checked twice?

2021-04-14 11:18 UTC, Nikitzu commented on rslang/src/app/games/savannah/components/savannah/savannah.component.html
> +          <label> Pick group:</label>
unnecessary space in tag

2021-04-14 11:18 UTC, Nikitzu commented on rslang/src/app/games/savannah/components/savannah/savannah.component.html
> +            <option *ngFor="let group of groups;" [value]="group">{{+group + 1}}</option>
group is a number??? strange name

2021-04-14 11:18 UTC, Nikitzu commented on rslang/src/app/games/savannah/components/savannah/savannah.component.ts
> +    }, 0);
0?????

2021-04-14 11:18 UTC, Nikitzu commented on rslang/src/app/games/savannah/components/savannah/savannah.component.ts
> +    if (e.key === '1' || e.key === '2' || e.key === '3' || e.key === '4') {
better to create an array and use includes.

2021-04-14 11:18 UTC, Nikitzu commented on rslang/src/app/games/savannah/components/savannah/savannah.component.ts
> +  onKeyDownHandler(e: KeyboardEvent): void {
e -> event

2021-04-14 11:18 UTC, Nikitzu commented on rslang/src/app/games/savannah/components/savannah/savannah.component.ts
> +    this.gameResultWords.incorrect_words.push(
incorrect_words??? What? maybe incorrectWords?

2021-04-14 11:18 UTC, Nikitzu commented on rslang/src/app/games/savannah/components/savannah/savannah.component.ts
> +    this.gameResultWords.correct_words.push(
same

2021-04-14 11:18 UTC, Nikitzu commented on rslang/src/app/games/savannah/components/savannah/savannah.component.ts
> +    for (let i = arr.length - 1; i > 0; i -= 1) {
i--

2021-04-14 11:18 UTC, Nikitzu commented on rslang/src/app/games/savannah/components/savannah/savannah.component.ts
> +    const incorrectNumber: number = this.gameResultWords.incorrect_words.length;
correct_words, incorrect_words???

2021-04-14 11:18 UTC, Nikitzu commented on rslang/src/app/shared/constants/constants.ts
> +export const Pages: string[] = [
What do we use this array for? It is bad approach to create pages array like that

2021-04-14 11:24 UTC, Nikitzu requested changes

2021-04-14 11:24 UTC, Nikitzu commented on rslang/src/app/shared/constants/constants.ts
> +  '29',
What will happen if there will be more than 29 pages?

2021-04-14 14:18 UTC, Nikitzu requested changes

2021-04-14 14:18 UTC, Nikitzu commented on rslang/src/app/games/savannah/components/savannah/savannah.component.html
> +    <div class="game__menu" *ngIf="!isGameEnd">
Hm. I belive that when isGameStart = false then isGameEnd = true and vice versa. No?

2021-04-14 14:18 UTC, Nikitzu commented on rslang/src/app/games/savannah/components/savannah/savannah.component.html
> +          <select [(ngModel)]="group" class="savannah__select">
and ngModel still for group?

2021-04-14 14:18 UTC, Nikitzu commented on rslang/src/app/games/savannah/components/savannah/savannah.component.ts
> +/* eslint no-plusplus: ["error", { "allowForLoopAfterthoughts": true }] */
WHAT?

2021-04-14 14:18 UTC, Nikitzu commented on rslang/src/app/games/savannah/components/savannah/savannah.component.ts
> +    this.gameWordsService.sortedWords$.subscribe(
Where is unsubscribe?

2021-04-14 14:18 UTC, Nikitzu commented on rslang/src/app/games/savannah/components/savannah/savannah.component.ts
> +      changedWord.userStats.optional.knowledgeDegree = (changedWord.userStats.optional.knowledgeDegree as number) + 1;
So, if I understand right you change property type here? Why?

2021-04-14 15:37 UTC, nofishtou commented on rslang/src/app/games/savannah/components/savannah/savannah.component.ts
> +      changedWord.userStats.optional.knowledgeDegree = (changedWord.userStats.optional.knowledgeDegree as number) + 1;
Because it can be undefined. This model wasn't written by me. I don't know why it has type number | undefined .

2021-04-14 15:38 UTC, nofishtou commented on rslang/src/app/games/savannah/components/savannah/savannah.component.ts
> +/* eslint no-plusplus: ["error", { "allowForLoopAfterthoughts": true }] */
Updated eslint rule for all file.

2021-04-14 17:02 UTC, Nikitzu requested changes

2021-04-14 17:02 UTC, Nikitzu commented on rslang/src/app/games/savannah/components/savannah/savannah.component.ts
> +      changedWord.userStats.optional.knowledgeDegree = (changedWord.userStats.optional.knowledgeDegree as number) + 1;
lol

2021-04-15 15:08 UTC, Nikitzu approved these changes

2021-04-15 18:04 UTC, merged