New design
whattablackhole/rslang-archive- pull request #72
Opened 2021-04-15 15:27 UTC by EvilKami7

2021-04-15 18:13 UTC, Nikitzu requested changes

2021-04-15 18:13 UTC, Nikitzu commented on rslang/src/app/components/main/main.html
> +      <mat-expansion-panel (opened)="panelOpenState = true" (closed)="panelOpenState = false">
seems like we have unnecessary spaces here

2021-04-16 06:06 UTC, coriander31415 approved these changes

2021-04-16 15:00 UTC, kastrubait approved these changes

2021-04-16 15:24 UTC, Nikitzu approved these changes

2021-04-16 16:42 UTC, merged