Fix statistics
whattablackhole/rslang-archive- pull request #82
Opened 2021-04-17 16:07 UTC by EvilKami7

2021-04-17 16:19 UTC, Anntol commented on rslang/src/app/core/services/base-data.service.ts
> +        console.log('Does not find info');
Please use notification service instead of console.log if we need this errors

2021-04-17 17:57 UTC, Nikitzu requested changes

2021-04-17 17:57 UTC, Nikitzu commented on rslang/src/app/core/services/base-data.service.ts
> +      .subscribe((data: T) => {
why do we need subscribe in Base service???

2021-04-17 17:57 UTC, Nikitzu commented on rslang/src/app/statistics/components/statistics-page/statistics-page.component.ts
> +    this.gsProvider.getGameSessions()
where is unsubscribe?

2021-04-17 17:57 UTC, Nikitzu commented on rslang/src/app/statistics/components/statistics-page/statistics-page.component.ts
> +          if (this.gameSessions !== undefined) {
if (!this.gameSessions)

2021-04-17 17:57 UTC, Nikitzu commented on rslang/src/app/statistics/services/gs-provider.service.ts
>      return this.data$;
WHAT?

2021-04-17 18:41 UTC, EvilKami7 commented on rslang/src/app/core/services/base-data.service.ts
> +      .subscribe((data: T) => {
it was implemented by @whattablackhole. And this method was presented on discord call

2021-04-17 18:47 UTC, Nikitzu approved these changes

2021-04-18 08:01 UTC, Anntol approved these changes

2021-04-18 14:45 UTC, merged