[Ebook] routing finish
whattablackhole/rslang-archive- pull request #83
Opened 2021-04-17 17:00 UTC by kastrubait

the transfer of the parameter from the textbook to the games is implemented

2021-04-17 17:55 UTC, Nikitzu requested changes

2021-04-17 17:55 UTC, Nikitzu commented on rslang/src/app/ebook/components/ebook-header/ebook-header.component.ts
> +    return 0;
return this.groupSlider.tickInterval | 0

2021-04-17 17:55 UTC, Nikitzu commented on rslang/src/app/ebook/components/game-sidenav/game-sidenav.component.ts
> +    return 1;
what?????

2021-04-17 17:55 UTC, Nikitzu commented on rslang/src/app/ebook/services/ebook-data.service.ts
> +export class EbookDataService {
Why it doesn't inherited from base data service?

2021-04-18 11:28 UTC, Nikitzu approved these changes

2021-04-18 11:49 UTC, coriander31415 approved these changes

2021-04-18 12:16 UTC, merged